name: Testing

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths-ignore:
      - '**.md'
      - 'docs/**'

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: [team-flutter]
    outputs:
      version: ${{ steps.meta.outputs.version }}
      version-title: ${{ steps.meta.outputs.version-title }}
    steps:
      - uses: AdGuardSoftwareLimited/actions/actions/epoch-version-metadata@master
        id: meta

  check-fixme:
    uses: AdGuardSoftwareLimited/actions/.github/workflows/check-fixme.yml@master
    with:
      team: flutter

  lint:
    uses: ./.github/workflows/flutter-lint.yml
    with:
      prepare-script: make init
    secrets: inherit

  test:
    uses: ./.github/workflows/flutter-test.yml
    secrets: inherit

  build-android:
    needs: [prepare]
    uses: ./.github/workflows/flutter-build-android.yml
    secrets: inherit
    with:
      channel: nightly
      vault-role: trusttunnel-app
      version: ${{ needs.prepare.outputs.version }}
      build-number: ${{ github.run_number }}
      version-title: ${{ needs.prepare.outputs.version-title }}
      build-mode: apk
      artifact-name: trusttunnel-android-pr
      artifact-path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    needs: [prepare]
    if: >-
      github.event.pull_request.draft == false
    uses: ./.github/workflows/flutter-build-ios.yml
    secrets: inherit
    with:
      channel: nightly
      version: ${{ needs.prepare.outputs.version }}
      build-number: ${{ github.run_number }}
      version-title: ${{ needs.prepare.outputs.version-title }}
      build-mode: adhoc
      artifact-name: trusttunnel-ios-pr
      artifact-path: ios/build/TrustTunnel.ipa

  build-macos:
    needs: [prepare]
    if: >-
      github.event.pull_request.draft == false
    uses: ./.github/workflows/flutter-build-macos.yml
    secrets: inherit
    with:
      channel: nightly
      version: ${{ needs.prepare.outputs.version }}
      build-number: ${{ github.run_number }}
      version-title: ${{ needs.prepare.outputs.version-title }}
      macos-signing-type: developer_id
      artifact-name: trusttunnel-macos-pr
      artifact-path: macos/build/TrustTunnel.dmg

  build-windows:
    if: >-
      github.event.pull_request.draft == false
    uses: ./.github/workflows/flutter-build-windows.yml
    with:
      artifact-name: trusttunnel-windows-pr
      artifact-path: build/windows/x64/runner/Release/**

  build-linux:
    if: >-
      github.event.pull_request.draft == false
    uses: ./.github/workflows/flutter-build-linux.yml
    secrets: inherit
    with:
      artifact-name: trusttunnel-linux-pr
      artifact-path: build/linux/x64/release/bundle/**
